events {}

http {
    server {
        listen 80;

        # Route /api/* to the api service
        location /api/ {
            proxy_pass http://api:4000/;
        }

        # Route / to the web service
        location / {
            proxy_pass http://web:3000/;
        }
    }
}